# Generated by Django 5.2.5 on 2025-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ta', models.CharField(blank=True, max_length=200, null=True)),
                ('advantages_en', models.TextField()),
                ('advantages_ta', models.TextField(blank=True, null=True)),
                ('disadvantages_en', models.TextField()),
                ('disadvantages_ta', models.TextField(blank=True, null=True)),
                ('dosage_timing_en', models.CharField(max_length=200)),
                ('dosage_timing_ta', models.CharField(blank=True, max_length=200, null=True)),
                ('age_group_en', models.CharField(max_length=100)),
                ('age_group_ta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
