# Generated by Django 5.2.5 on 2025-08-29 08:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_dis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablet',
            options={'ordering': ['name_en'], 'verbose_name': 'Tablet', 'verbose_name_plural': 'Tablets'},
        ),
        migrations.AddField(
            model_name='tablet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='advantages_en',
            field=models.TextField(help_text='Benefits and uses in English'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='advantages_ta',
            field=models.TextField(blank=True, help_text='Benefits and uses in Tamil', null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='age_group_en',
            field=models.CharField(help_text='Recommended age group in English', max_length=100),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='age_group_ta',
            field=models.CharField(blank=True, help_text='Recommended age group in Tamil', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='disadvantages_en',
            field=models.TextField(help_text='Side effects and precautions in English'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='disadvantages_ta',
            field=models.TextField(blank=True, help_text='Side effects and precautions in Tamil', null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='dosage_timing_en',
            field=models.TextField(help_text='Dosage instructions in English', max_length=500),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='dosage_timing_ta',
            field=models.TextField(blank=True, help_text='Dosage instructions in Tamil', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name_en',
            field=models.CharField(help_text='English name of the tablet', max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name_ta',
            field=models.CharField(blank=True, help_text='Tamil name of the tablet', max_length=200, null=True),
        ),
    ]
