# Generated by Django 5.2.5 on 2025-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_dis', '0002_alter_tablet_options_tablet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='interactions_en',
            field=models.TextField(blank=True, help_text='Drug interactions in English', null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='interactions_ta',
            field=models.TextField(blank=True, help_text='Drug interactions in Tamil', null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='storage_en',
            field=models.TextField(blank=True, help_text='Storage instructions in English', null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='storage_ta',
            field=models.TextField(blank=True, help_text='Storage instructions in Tamil', null=True),
        ),
    ]
