# Generated by Django 5.2.5 on 2025-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_dis', '0003_tablet_interactions_en_tablet_interactions_ta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='dosage_timing_ta',
        ),
        migrations.AddField(
            model_name='tablet',
            name='dosage_ta',
            field=models.TextField(blank=True, help_text='Dosage instructions in Tamil', max_length=500, null=True),
        ),
    ]
