# Generated by Django 5.2.5 on 2025-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_dis', '0004_remove_tablet_dosage_timing_ta_tablet_dosage_ta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablet',
            options={},
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='dosage_ta',
        ),
        migrations.AddField(
            model_name='tablet',
            name='dosage_timing_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='advantages_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='advantages_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='age_group_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='age_group_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='disadvantages_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='disadvantages_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='dosage_timing_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='interactions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='interactions_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
